- id: "pre-commit-pipreqs"
  name: "Pipreqs Hook"
  entry: run-pipreqs-hook.sh
  types: ["file", "non-executable", "python", "text"]
  exclude: ".yaml$|.yml$"
  language: "script"
  description: "This is an example hook to demonstrate how to create a pre-commit hook"
  args: [--example1, --example2]